/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharFilterhtmlStrip } from '../models/CharFilterhtmlStrip';
import { CharFiltericuNormalize } from '../models/CharFiltericuNormalize';
import { CharFiltermapping } from '../models/CharFiltermapping';
import { CharFiltermappingMappings } from '../models/CharFiltermappingMappings';
import { CharFilterpersian } from '../models/CharFilterpersian';
import { HttpFile } from '../http/http';

export class ApiAtlasFTSAnalyzersViewManualCharFiltersInner {
    /**
    * The HTML tags that you want to exclude from filtering.
    */

    'ignoredTags'?: Array<string>;
    /**
    * Human-readable label that identifies this character filter type.
    */

    'type': string;

    'mappings': CharFiltermappingMappings;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ignoredTags",
            "baseName": "ignoredTags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "mappings",
            "baseName": "mappings",
            "type": "CharFiltermappingMappings",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiAtlasFTSAnalyzersViewManualCharFiltersInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiAtlasFTSAnalyzersViewManualCharFiltersInnerTypeEnum = "persian" ;

