/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Index specifications for the collection's fields.
*/
export class ApiAtlasFTSMappingsViewManual {
    /**
    * Flag that indicates whether the index uses dynamic or static mappings. Required if **mappings.fields** is omitted.
    */
    'dynamic'?: boolean;
    /**
    * One or more field specifications for the Atlas Search index. Required if **mappings.dynamic** is omitted or set to **false**.
    */
    'fields'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dynamic",
            "baseName": "dynamic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiAtlasFTSMappingsViewManual.attributeTypeMap;
    }

    public constructor() {
    }
}

