/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApiOrganizationInvitationUpdateRequestView {
    /**
    * One or more organization or project level roles to assign to the MongoDB Cloud user.
    */

    'roles'?: Set<string>;
    /**
    * List of teams to which you want to invite the desired MongoDB Cloud user.
    */

    'teamIds'?: Set<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "teamIds",
            "baseName": "teamIds",
            "type": "Set<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiOrganizationInvitationUpdateRequestView.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiOrganizationInvitationUpdateRequestViewRolesEnum = "ORG_OWNER" | "ORG_MEMBER" | "ORG_GROUP_CREATOR" | "ORG_BILLING_ADMIN" | "ORG_READ_ONLY" ;

