/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Specifications for one policy.
*/
export class ApiPolicyItemView {
    /**
    * Number that indicates the frequency interval for a set of snapshots. A value of `1` specifies the first instance of the corresponding `frequencyType`.  - In a monthly policy item, `1` indicates that the monthly snapshot occurs on the first day of the month and `40` indicates the last day of the month.  - In a weekly policy item, `1` indicates that the weekly snapshot occurs on Monday and `7` indicates Sunday.  - In an hourly policy item, you can set the frequency interval to `1`, `2`, `4`, `6`, `8`, or `12`. For hourly policy items for NVMe clusters, MongoDB Cloud only accepts `12` as the frequency interval value.
    */

    'frequencyInterval': number;
    /**
    * Human-readable label that identifies the frequency type associated with the backup policy.
    */

    'frequencyType': string;
    /**
    * Unique 24-hexadecimal digit string that identifies this backup policy item.
    */

    'id'?: string;
    /**
    * Unit of time in which MongoDB Cloud measures snapshot retention.
    */

    'retentionUnit': string;
    /**
    * Duration in days, weeks, or months that MongoDB Cloud retains the snapshot. For less frequent policy items, MongoDB Cloud requires that you specify a value greater than or equal to the value specified for more frequent policy items.  For example: If the hourly policy item specifies a retention of two days, you must specify two days or greater for the retention of the weekly policy item.
    */

    'retentionValue': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "frequencyInterval",
            "baseName": "frequencyInterval",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "frequencyType",
            "baseName": "frequencyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "retentionUnit",
            "baseName": "retentionUnit",
            "type": "string",
            "format": ""
        },
        {
            "name": "retentionValue",
            "baseName": "retentionValue",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ApiPolicyItemView.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiPolicyItemViewFrequencyIntervalEnum = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "20" | "21" | "22" | "23" | "24" | "25" | "26" | "27" | "28" | "40" ;
export type ApiPolicyItemViewFrequencyTypeEnum = "daily" | "hourly" | "monthly" | "weekly" | "ondemand" ;
export type ApiPolicyItemViewRetentionUnitEnum = "days" | "weeks" | "months" ;

