/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from '../models/Link';
import { HttpFile } from '../http/http';

/**
* Key and value pair that map one restore file to one hashed checksum. This parameter applies after you download the corresponding **delivery.url**.
*/
export class ApiRestoreJobFileHashView {
    /**
    * Human-readable label that identifies the hashed file.
    */
    'fileName'?: string;
    /**
    * Hashed checksum that maps to the restore file.
    */
    'hash'?: string;
    /**
    * List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    */
    'links'?: Array<Link>;
    /**
    * Human-readable label that identifies the hashing algorithm used to compute the hash value.
    */
    'typeName'?: ApiRestoreJobFileHashViewTypeNameEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "typeName",
            "baseName": "typeName",
            "type": "ApiRestoreJobFileHashViewTypeNameEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiRestoreJobFileHashView.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiRestoreJobFileHashViewTypeNameEnum = "SHA1" ;

