/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Method and details that indicate how to deliver the restored snapshot data.
*/
export class ApiRestoreJobDeliveryView {
    /**
    * Header name to use when downloading the restore, used with `\"delivery.methodName\" : \"HTTP\"`.
    */
    'authHeader'?: string;
    /**
    * Header value to use when downloading the restore, used with `\"delivery.methodName\" : \"HTTP\"`.
    */
    'authValue'?: string;
    /**
    * Number of hours after the restore job completes that indicates when the Uniform Resource Locator (URL) for the snapshot download file expires. The resource returns this parameter when `\"delivery.methodName\" : \"HTTP\"`.
    */
    'expirationHours'?: number;
    /**
    * Date and time when the Uniform Resource Locator (URL) for the snapshot download file expires. This parameter expresses its value in the ISO 8601 timestamp format in UTC. The resource returns this parameter when `\"delivery.methodName\" : \"HTTP\"`.
    */
    'expires'?: Date;
    /**
    * Positive integer that indicates how many times you can use the Uniform Resource Locator (URL) for the snapshot download file. The resource returns this parameter when `\"delivery.methodName\" : \"HTTP\"`.
    */
    'maxDownloads'?: number;
    /**
    * Human-readable label that identifies the means for delivering the data. If you set `\"delivery.methodName\" : \"AUTOMATED_RESTORE\"`, you must also set: **delivery.targetGroupId** and **delivery.targetClusterName** or **delivery.targetClusterId**. The response returns `\"delivery.methodName\" : \"HTTP\"` as an automated restore uses HyperText Transport Protocol (HTTP) to deliver the restore job to the target host.
    */
    'methodName': ApiRestoreJobDeliveryViewMethodNameEnum;
    /**
    * State of the downloadable snapshot file when MongoDB Cloud received this request.
    */
    'statusName'?: ApiRestoreJobDeliveryViewStatusNameEnum;
    /**
    * Unique 24-hexadecimal digit string that identifies the target cluster. Use the **clusterId** returned in the response body of the **Get All Snapshots** and **Get a Snapshot** endpoints. This parameter applies when `\"delivery.methodName\" : \"AUTOMATED_RESTORE\"`.   If the target cluster doesn't have backup enabled, two resources return parameters with empty values:  - **Get All Snapshots** endpoint returns an empty results array without **clusterId** elements - **Get a Snapshot** endpoint doesn't return a **clusterId** parameter.  To return a response with the **clusterId** parameter, either use the **delivery.targetClusterName** parameter or enable backup on the target cluster.
    */
    'targetClusterId'?: string;
    /**
    * Human-readable label that identifies the target cluster. Use the **clusterName** returned in the response body of the **Get All Snapshots** and **Get a Snapshot** endpoints.  This parameter applies when `\"delivery.methodName\" : \"AUTOMATED_RESTORE\"`.  If the target cluster doesn't have backup enabled, two resources return parameters with empty values:  - **Get All Snapshots** endpoint returns an empty results array without **clusterId** elements - **Get a Snapshot** endpoint doesn't return a **clusterId** parameter.  To return a response with the **clusterId** parameter, either use the **delivery.targetClusterName** parameter or enable backup on the target cluster.
    */
    'targetClusterName'?: string;
    /**
    * Unique 24-hexadecimal digit string that identifies the project that contains the destination cluster for the restore job. The resource returns this parameter when `\"delivery.methodName\" : \"AUTOMATED_RESTORE\"`.
    */
    'targetGroupId'?: string;
    /**
    * Uniform Resource Locator (URL) from which you can download the restored snapshot data. Url includes the verification key. The resource returns this parameter when `\"delivery.methodName\" : \"HTTP\"`.
    */
    'url'?: string;
    /**
    * Uniform Resource Locator (URL) from which you can download the restored snapshot data. This should be preferred over **url**. The verification key must be sent as an HTTP header. The resource returns this parameter when `\"delivery.methodName\" : \"HTTP\"`.
    */
    'urlV2'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "authHeader",
            "baseName": "authHeader",
            "type": "string",
            "format": ""
        },
        {
            "name": "authValue",
            "baseName": "authValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "expirationHours",
            "baseName": "expirationHours",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "expires",
            "baseName": "expires",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "maxDownloads",
            "baseName": "maxDownloads",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "methodName",
            "baseName": "methodName",
            "type": "ApiRestoreJobDeliveryViewMethodNameEnum",
            "format": ""
        },
        {
            "name": "statusName",
            "baseName": "statusName",
            "type": "ApiRestoreJobDeliveryViewStatusNameEnum",
            "format": ""
        },
        {
            "name": "targetClusterId",
            "baseName": "targetClusterId",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetClusterName",
            "baseName": "targetClusterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetGroupId",
            "baseName": "targetGroupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlV2",
            "baseName": "urlV2",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiRestoreJobDeliveryView.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiRestoreJobDeliveryViewMethodNameEnum = "CLIENT_PIT_HTTP" | "QUERY" | "AUTOMATED_RESTORE" | "HTTP" | "THIRD_PARTY_COPY" | "CLIENT_PIT_SCP" | "SCP" ;
export type ApiRestoreJobDeliveryViewStatusNameEnum = "NOT_STARTED" | "IN_PROGRESS" | "READY" | "FAILED" | "INTERRUPTED" | "EXPIRED" | "MAX_DOWNLOADS_EXCEEDED" ;

