/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvailableDeploymentView } from '../models/AvailableDeploymentView';
import { HttpFile } from '../http/http';

export class AvailableProjectView {
    /**
    * List of clusters that can be migrated to MongoDB Cloud.
    */
    'deployments'?: Array<AvailableDeploymentView>;
    /**
    * Hostname of MongoDB Agent list that you configured to perform a migration.
    */
    'migrationHosts'?: Array<string>;
    /**
    * Human-readable label that identifies this project.
    */
    'name': string;
    /**
    * Unique 24-hexadecimal digit string that identifies the project to be migrated.
    */
    'projectId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deployments",
            "baseName": "deployments",
            "type": "Array<AvailableDeploymentView>",
            "format": ""
        },
        {
            "name": "migrationHosts",
            "baseName": "migrationHosts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvailableProjectView.attributeTypeMap;
    }

    public constructor() {
    }
}

