/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Settings needed to configure the MongoDB Connector for Business Intelligence for this cluster.
*/
export class BiConnector {
    /**
    * Flag that indicates whether MongoDB Connector for Business Intelligence is enabled on the specified cluster.
    */
    'enabled'?: boolean;
    /**
    * Data source node designated for the MongoDB Connector for Business Intelligence on MongoDB Cloud. The MongoDB Connector for Business Intelligence on MongoDB Cloud reads data from the primary, secondary, or analytics node based on your read preferences. Defaults to `ANALYTICS` node, or `SECONDARY` if there are no `ANALYTICS` nodes.
    */
    'readPreference'?: BiConnectorReadPreferenceEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "readPreference",
            "baseName": "readPreference",
            "type": "BiConnectorReadPreferenceEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BiConnector.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BiConnectorReadPreferenceEnum = "PRIMARY" | "SECONDARY" | "ANALYTICS" ;

