/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Unique identifier of event type.
*/
export type BillingEventTypeViewForNdsGroup = "CREDIT_CARD_CURRENT" | "CREDIT_CARD_ABOUT_TO_EXPIRE" | "PENDING_INVOICE_UNDER_THRESHOLD" | "PENDING_INVOICE_OVER_THRESHOLD" | "DAILY_BILL_UNDER_THRESHOLD" | "DAILY_BILL_OVER_THRESHOLD" | "CHARGE_SUCCEEDED" | "CHARGE_FAILED" | "CHARGE_PROCESSING" | "CHARGE_PENDING_REVERSAL" | "BRAINTREE_CHARGE_FAILED" | "INVOICE_CLOSED" | "CHECK_PAYMENT_RECEIVED" | "WIRE_TRANSFER_PAYMENT_RECEIVED" | "DISCOUNT_APPLIED" | "CREDIT_ISSUED" | "CREDIT_PULLED_FWD" | "CREDIT_START_DATE_MODIFIED" | "CREDIT_END_DATE_MODIFIED" | "CREDIT_ELASTIC_INVOICING_MODIFIED" | "CREDIT_TYPE_MODIFIED" | "CREDIT_AMOUNT_CENTS_MODIFIED" | "CREDIT_AMOUNT_REMAINING_CENTS_MODIFIED" | "CREDIT_TOTAL_BILLED_CENTS_MODIFIED" | "CREDIT_AWS_CUSTOMER_ID_MODIFIED" | "CREDIT_AWS_PRODUCT_CODE_MODIFIED" | "CREDIT_GCP_MARKETPLACE_ENTITLEMENT_ID_MODIFIED" | "CREDIT_AZURE_SUBSCRIPTION_ID_MODIFIED" | "PROMO_CODE_APPLIED" | "PAYMENT_FORGIVEN" | "REFUND_ISSUED" | "ACCOUNT_DOWNGRADED" | "ACCOUNT_UPGRADED" | "ACCOUNT_MODIFIED" | "SUPPORT_PLAN_ACTIVATED" | "SUPPORT_PLAN_CANCELLED" | "SUPPORT_PLAN_CANCELLATION_SCHEDULED" | "INITIATE_SALESFORCE_SERVICE_CLOUD_SYNC" | "INVOICE_ADDRESS_CHANGED" | "INVOICE_ADDRESS_ADDED" | "PREPAID_PLAN_ACTIVATED" | "ELASTIC_INVOICING_MODE_ACTIVATED" | "ELASTIC_INVOICING_MODE_DEACTIVATED" | "TERMINATE_PAID_SERVICES" | "BILLING_EMAIL_ADDRESS_ADDED" | "BILLING_EMAIL_ADDRESS_CHANGED" | "BILLING_EMAIL_ADDRESS_REMOVED" ;
