/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.  The Atlas Administration API uses HTTP Digest Authentication to authenticate requests. Provide a programmatic API public key and corresponding private key as the username and password when constructing the HTTP request. For example, to [return database access history](#tag/Access-Tracking/operation/listAccessLogsByClusterName) with [cURL](https://en.wikipedia.org/wiki/CURL), run the following command in the terminal:  ``` curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\   --digest \\   --header \"Accept: application/vnd.atlas.2023-02-01+json\" \\   GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/dbAccessHistory/clusters/{clusterName}?pretty=true\" ```  To learn more, see [Get Started with the Atlas Administration API](https://www.mongodb.com/docs/atlas/configure-api-access/). For support, see [MongoDB Support](https://www.mongodb.com/support/get-started).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingPayment } from '../models/BillingPayment';
import { BillingRefund } from '../models/BillingRefund';
import { InvoiceLineItem } from '../models/InvoiceLineItem';
import { Link } from '../models/Link';
import { HttpFile } from '../http/http';

export class BillingInvoice {
    /**
    * Sum of services that the specified organization consumed in the period covered in this invoice. This parameter expresses its value in cents (100ths of one US Dollar) and calculates its value as **subtotalCents** + **salesTaxCents** - **startingBalanceCents**.
    */

    'amountBilledCents'?: number;
    /**
    * Sum that the specified organization paid toward this invoice. This parameter expresses its value in cents (100ths of one US Dollar).
    */

    'amountPaidCents'?: number;
    /**
    * Date and time when MongoDB Cloud created this invoice. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    */

    'created'?: Date;
    /**
    * Sum that MongoDB credited the specified organization toward this invoice. This parameter expresses its value in cents (100ths of one US Dollar).
    */

    'creditsCents'?: number;
    /**
    * Date and time when MongoDB Cloud finished the billing period that this invoice covers. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    */

    'endDate'?: Date;
    /**
    * Unique 24-hexadecimal digit string that identifies the project associated to this invoice. This identifying string doesn't appear on all invoices.
    */

    'groupId'?: string;
    /**
    * Unique 24-hexadecimal digit string that identifies the invoice submitted to the specified organization. Charges typically post the next day.
    */

    'id'?: string;
    /**
    * List that contains individual services included in this invoice.
    */

    'lineItems'?: Array<InvoiceLineItem>;
    /**
    * List that contains the invoices for organizations linked to the paying organization.
    */

    'linkedInvoices'?: Array<BillingInvoice>;
    /**
    * List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    */

    'links'?: Array<Link>;
    /**
    * Unique 24-hexadecimal digit string that identifies the organization charged for services consumed from MongoDB Cloud.
    */

    'orgId'?: string;
    /**
    * List that contains funds transferred to MongoDB to cover the specified service noted in this invoice.
    */

    'payments'?: Array<BillingPayment>;
    /**
    * List that contains payments that MongoDB returned to the organization for this invoice.
    */

    'refunds'?: Array<BillingRefund>;
    /**
    * Sum of sales tax applied to this invoice. This parameter expresses its value in cents (100ths of one US Dollar).
    */

    'salesTaxCents'?: number;
    /**
    * Date and time when MongoDB Cloud began the billing period that this invoice covers. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    */

    'startDate'?: Date;
    /**
    * Sum that the specified organization owed to MongoDB when MongoDB issued this invoice. This parameter expresses its value in US Dollars.
    */

    'startingBalanceCents'?: number;
    /**
    * Phase of payment processing in which this invoice exists when you made this request. Accepted phases include:  | Phase Value | Reason | |---|---| | CLOSED | MongoDB finalized all charges in the billing cycle but has yet to charge the customer. | | FAILED | MongoDB attempted to charge the provided credit card but charge for that amount failed. | | FORGIVEN | Customer initiated payment which MongoDB later forgave. | | FREE | All charges totalled zero so the customer won't be charged. | | INVOICED | MongoDB handled these charges using elastic invoicing. | | PAID | MongoDB succeeded in charging the provided credit card. | | PENDING | Invoice includes charges for the current billing cycle. | | PREPAID | Customer has a pre-paid plan so they won't be charged. | 
    */

    'statusName'?: string;
    /**
    * Sum of all positive invoice line items contained in this invoice. This parameter expresses its value in cents (100ths of one US Dollar).
    */

    'subtotalCents'?: number;
    /**
    * Date and time when MongoDB Cloud last updated the value of this payment. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    */

    'updated'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amountBilledCents",
            "baseName": "amountBilledCents",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "amountPaidCents",
            "baseName": "amountPaidCents",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "creditsCents",
            "baseName": "creditsCents",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lineItems",
            "baseName": "lineItems",
            "type": "Array<InvoiceLineItem>",
            "format": ""
        },
        {
            "name": "linkedInvoices",
            "baseName": "linkedInvoices",
            "type": "Array<BillingInvoice>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<BillingPayment>",
            "format": ""
        },
        {
            "name": "refunds",
            "baseName": "refunds",
            "type": "Array<BillingRefund>",
            "format": ""
        },
        {
            "name": "salesTaxCents",
            "baseName": "salesTaxCents",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startingBalanceCents",
            "baseName": "startingBalanceCents",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "statusName",
            "baseName": "statusName",
            "type": "string",
            "format": ""
        },
        {
            "name": "subtotalCents",
            "baseName": "subtotalCents",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return BillingInvoice.attributeTypeMap;
    }

    public constructor() {
    }
}

