/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.  The Atlas Administration API uses HTTP Digest Authentication to authenticate requests. Provide a programmatic API public key and corresponding private key as the username and password when constructing the HTTP request. For example, to [return database access history](#tag/Access-Tracking/operation/listAccessLogsByClusterName) with [cURL](https://en.wikipedia.org/wiki/CURL), run the following command in the terminal:  ``` curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\   --digest \\   --header \"Accept: application/vnd.atlas.2023-02-01+json\" \\   GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/dbAccessHistory/clusters/{clusterName}?pretty=true\" ```  To learn more, see [Get Started with the Atlas Administration API](https://www.mongodb.com/docs/atlas/configure-api-access/). For support, see [MongoDB Support](https://www.mongodb.com/support/get-started).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CloudAccessRoleAssignment } from '../models/CloudAccessRoleAssignment';
import { Link } from '../models/Link';
import { HttpFile } from '../http/http';

export class CloudAppUser {
    /**
    * Two alphabet characters that identifies MongoDB Cloud user's geographic location. This parameter uses the ISO 3166-1a2 code format.
    */

    'country': string;
    /**
    * Date and time when the current account is created. This value is in the ISO 8601 timestamp format in UTC.
    */

    'createdAt'?: Date;
    /**
    * Email address that belongs to the MongoDB Cloud user.
    */

    'emailAddress': string;
    /**
    * First or given name that belongs to the MongoDB Cloud user.
    */

    'firstName': string;
    /**
    * Unique 24-hexadecimal digit string that identifies the MongoDB Cloud user.
    */

    'id'?: string;
    /**
    * Date and time when the current account last authenticated. This value is in the ISO 8601 timestamp format in UTC.
    */

    'lastAuth'?: Date;
    /**
    * Last name, family name, or surname that belongs to the MongoDB Cloud user.
    */

    'lastName': string;
    /**
    * List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    */

    'links'?: Array<Link>;
    /**
    * Mobile phone number that belongs to the MongoDB Cloud user.
    */

    'mobileNumber': string;
    /**
    * Password applied with the username to log in to MongoDB Cloud. MongoDB Cloud does not return this parameter except in response to creating a new MongoDB Cloud user. Only the MongoDB Cloud user can update their password after it has been set from the MongoDB Cloud console.
    */

    'password': string;
    /**
    * List of objects that display the MongoDB Cloud user's roles and the corresponding organization or project to which that role applies. A role can apply to one organization or one project but not both.
    */

    'roles'?: Array<CloudAccessRoleAssignment>;
    /**
    * List of unique 24-hexadecimal digit strings that identifies the teams to which this MongoDB Cloud user belongs.
    */

    'teamIds'?: Set<string>;
    /**
    * Email address that represents the username of the MongoDB Cloud user.
    */

    'username': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string",
            "format": "email"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastAuth",
            "baseName": "lastAuth",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "mobileNumber",
            "baseName": "mobileNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<CloudAccessRoleAssignment>",
            "format": ""
        },
        {
            "name": "teamIds",
            "baseName": "teamIds",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": "email"
        }    ];

    static getAttributeTypeMap() {
        return CloudAppUser.attributeTypeMap;
    }

    public constructor() {
    }
}

