/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CloudProviderAccessFeatureUsageExportSnapshotFeatureId } from '../models/CloudProviderAccessFeatureUsageExportSnapshotFeatureId';
import { HttpFile } from '../http/http';

/**
* Details that describe the Amazon Web Services (AWS) Simple Storage Service (S3) export buckets linked to this AWS Identity and Access Management (IAM) role.
*/
export class CloudProviderAccessExportSnapshotFeatureUsage {

    'featureId'?: CloudProviderAccessFeatureUsageExportSnapshotFeatureId;
    /**
    * Human-readable label that describes one MongoDB Cloud feature linked to this Amazon Web Services (AWS) Identity and Access Management (IAM) role.
    */

    'featureType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "featureId",
            "baseName": "featureId",
            "type": "CloudProviderAccessFeatureUsageExportSnapshotFeatureId",
            "format": ""
        },
        {
            "name": "featureType",
            "baseName": "featureType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CloudProviderAccessExportSnapshotFeatureUsage.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CloudProviderAccessExportSnapshotFeatureUsageFeatureTypeEnum = "ATLAS_DATA_LAKE" | "ENCRYPTION_AT_REST" | "EXPORT_SNAPSHOT" ;

