/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FederatedUserView } from '../models/FederatedUserView';
import { RoleMappingView } from '../models/RoleMappingView';
import { HttpFile } from '../http/http';

export class ConnectedOrgConfigView {
    /**
    * Approved domains that restrict users who can join the organization based on their email address.
    */
    'domainAllowList'?: Set<string>;
    /**
    * Value that indicates whether domain restriction is enabled for this connected org.
    */
    'domainRestrictionEnabled': boolean;
    /**
    * Unique 20-hexadecimal digit string that identifies the identity provider that this connected org config is associated with.
    */
    'identityProviderId': string;
    /**
    * Unique 24-hexadecimal digit string that identifies the connected organization configuration.
    */
    'orgId': string;
    /**
    * Atlas roles that are granted to a user in this organization after authenticating.
    */
    'postAuthRoleGrants'?: Set<ConnectedOrgConfigViewPostAuthRoleGrantsEnum>;
    /**
    * Role mappings that are configured in this organization.
    */
    'roleMappings'?: Set<RoleMappingView>;
    /**
    * List that contains the users who have an email address that doesn't match any domain on the allowed list.
    */
    'userConflicts'?: Array<FederatedUserView>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domainAllowList",
            "baseName": "domainAllowList",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "domainRestrictionEnabled",
            "baseName": "domainRestrictionEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "identityProviderId",
            "baseName": "identityProviderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string",
            "format": ""
        },
        {
            "name": "postAuthRoleGrants",
            "baseName": "postAuthRoleGrants",
            "type": "Set<ConnectedOrgConfigViewPostAuthRoleGrantsEnum>",
            "format": ""
        },
        {
            "name": "roleMappings",
            "baseName": "roleMappings",
            "type": "Set<RoleMappingView>",
            "format": ""
        },
        {
            "name": "userConflicts",
            "baseName": "userConflicts",
            "type": "Array<FederatedUserView>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectedOrgConfigView.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ConnectedOrgConfigViewPostAuthRoleGrantsEnum = "GLOBAL_AUTOMATION_ADMIN" | "GLOBAL_BACKUP_ADMIN" | "GLOBAL_METERING_USER" | "GLOBAL_METRICS_INTERNAL_USER" | "GLOBAL_MONITORING_ADMIN" | "GLOBAL_OWNER" | "GLOBAL_READ_ONLY" | "GLOBAL_USER_ADMIN" | "GLOBAL_USER_READ_ONLY" | "GLOBAL_ACCOUNT_SUSPENSION_ADMIN" | "GLOBAL_BILLING_ADMIN" | "GLOBAL_LEGAL_ADMIN" | "GLOBAL_FEATURE_FLAG_ADMIN" | "GLOBAL_ATLAS_TSE" | "GLOBAL_ATLAS_OPERATOR" | "GLOBAL_ATLAS_MONGODB_ROLLOUT_ADMIN" | "GLOBAL_ATLAS_ADMIN" | "GLOBAL_STITCH_ADMIN" | "GLOBAL_CHARTS_ADMIN" | "GLOBAL_EXPERIMENT_ASSIGNMENT_USER" | "GLOBAL_STITCH_INTERNAL_ADMIN" | "GLOBAL_BAAS_FEATURE_ADMIN" | "GLOBAL_SECURITY_ADMIN" | "GLOBAL_QUERY_ENGINE_INTERNAL_ADMIN" | "GLOBAL_PROACTIVE_SUPPORT_ADMIN" | "GLOBAL_INFRASTRUCTURE_INTERNAL_ADMIN" | "GLOBAL_SALESFORCE_ADMIN" | "GLOBAL_SALESFORCE_READ_ONLY" | "GLOBAL_APP_SERVICES_CLUSTER_DEBUG_DATA_ACCESS" | "ORG_MEMBER" | "ORG_READ_ONLY" | "ORG_BILLING_ADMIN" | "ORG_GROUP_CREATOR" | "ORG_OWNER" | "ORG_TEAM_MEMBERS_ADMIN" | "GROUP_AUTOMATION_ADMIN" | "GROUP_BACKUP_ADMIN" | "GROUP_MONITORING_ADMIN" | "GROUP_OWNER" | "GROUP_READ_ONLY" | "GROUP_USER_ADMIN" | "GROUP_BILLING_ADMIN" | "GROUP_DATA_ACCESS_ADMIN" | "GROUP_DATA_ACCESS_READ_ONLY" | "GROUP_DATA_ACCESS_READ_WRITE" | "GROUP_CHARTS_ADMIN" | "GROUP_CLUSTER_MANAGER" | "GROUP_SEARCH_INDEX_EDITOR" ;

