/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateGCPForwardingRuleRequest } from '../models/CreateGCPForwardingRuleRequest';
import { HttpFile } from '../http/http';

/**
* Group of Private Endpoint settings.
*/
export class CreateGCPEndpointGroupRequest {
    /**
    * Human-readable label that identifies a set of endpoints.
    */
    'endpointGroupName'?: string;
    /**
    * List of individual private endpoints that comprise this endpoint group.
    */
    'endpoints'?: Array<CreateGCPForwardingRuleRequest>;
    /**
    * Unique string that identifies the Google Cloud project in which you created the endpoints.
    */
    'gcpProjectId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "endpointGroupName",
            "baseName": "endpointGroupName",
            "type": "string",
            "format": ""
        },
        {
            "name": "endpoints",
            "baseName": "endpoints",
            "type": "Array<CreateGCPForwardingRuleRequest>",
            "format": ""
        },
        {
            "name": "gcpProjectId",
            "baseName": "gcpProjectId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateGCPEndpointGroupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

