/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DailyScheduleView {
    /**
    * Hour of the day when the scheduled window to run one online archive ends.
    */

    'endHour'?: number;
    /**
    * Minute of the hour when the scheduled window to run one online archive ends.
    */

    'endMinute'?: number;
    /**
    * Hour of the day when the when the scheduled window to run one online archive starts.
    */

    'startHour'?: number;
    /**
    * Minute of the hour when the scheduled window to run one online archive starts.
    */

    'startMinute'?: number;

    'type': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "endHour",
            "baseName": "endHour",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "endMinute",
            "baseName": "endMinute",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startHour",
            "baseName": "startHour",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startMinute",
            "baseName": "startMinute",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DailyScheduleView.attributeTypeMap;
    }

    public constructor() {
    }
}

