/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DBResource } from '../models/DBResource';
import { HttpFile } from '../http/http';

/**
* Privilege action that the role grants.
*/
export class DBAction {
    /**
    * Human-readable label that identifies the privilege action.
    */

    'action': string;
    /**
    * List of resources on which you grant the action.
    */

    'resources'?: Array<DBResource>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "resources",
            "baseName": "resources",
            "type": "Array<DBResource>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DBAction.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DBActionActionEnum = "FIND" | "INSERT" | "REMOVE" | "UPDATE" | "BYPASS_DOCUMENT_VALIDATION" | "USE_UUID" | "KILL_OP" | "CREATE_COLLECTION" | "CREATE_INDEX" | "DROP_COLLECTION" | "ENABLE_PROFILER" | "CHANGE_STREAM" | "COLL_MOD" | "COMPACT" | "CONVERT_TO_CAPPED" | "DROP_DATABASE" | "DROP_INDEX" | "RE_INDEX" | "RENAME_COLLECTION_SAME_DB" | "SET_USER_WRITE_BLOCK" | "BYPASS_USER_WRITE_BLOCK" | "LIST_SESSIONS" | "KILL_ANY_SESSION" | "COLL_STATS" | "CONN_POOL_STATS" | "DB_HASH" | "DB_STATS" | "GET_CMD_LINE_OPTS" | "GET_LOG" | "GET_PARAMETER" | "GET_SHARD_MAP" | "HOST_INFO" | "IN_PROG" | "LIST_DATABASES" | "LIST_COLLECTIONS" | "LIST_INDEXES" | "LIST_SHARDS" | "NET_STAT" | "REPL_SET_GET_CONFIG" | "REPL_SET_GET_STATUS" | "SERVER_STATUS" | "VALIDATE" | "SHARDING_STATE" | "TOP" | "SQL_GET_SCHEMA" | "SQL_SET_SCHEMA" | "VIEW_ALL_HISTORY" | "OUT_TO_S3" | "STORAGE_GET_CONFIG" | "STORAGE_SET_CONFIG" | "FLUSH_ROUTER_CONFIG" ;

