/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.  The Atlas Administration API uses HTTP Digest Authentication to authenticate requests. Provide a programmatic API public key and corresponding private key as the username and password when constructing the HTTP request. For example, to [return database access history](#tag/Access-Tracking/operation/listAccessLogsByClusterName) with [cURL](https://en.wikipedia.org/wiki/CURL), run the following command in the terminal:  ``` curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\   --digest \\   --header \"Accept: application/vnd.atlas.2023-02-01+json\" \\   GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/dbAccessHistory/clusters/{clusterName}?pretty=true\" ```  To learn more, see [Get Started with the Atlas Administration API](https://www.mongodb.com/docs/atlas/configure-api-access/). For support, see [MongoDB Support](https://www.mongodb.com/support/get-started).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Document that describes the destination of the migration.
*/
export class Destination {
    /**
    * Label that identifies the destination cluster.
    */

    'clusterName': string;
    /**
    * Unique 24-hexadecimal digit string that identifies the destination project.
    */

    'groupId': string;
    /**
    * The network type to use between the migration host and the target cluster.
    */

    'hostnameSchemaType': string;
    /**
    * Represents the endpoint to use when the host schema type is `PRIVATE_LINK`.
    */

    'privateLinkId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clusterName",
            "baseName": "clusterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "hostnameSchemaType",
            "baseName": "hostnameSchemaType",
            "type": "string",
            "format": ""
        },
        {
            "name": "privateLinkId",
            "baseName": "privateLinkId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Destination.attributeTypeMap;
    }

    public constructor() {
    }
}

