/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AWSKMS } from '../models/AWSKMS';
import { AzureKeyVault } from '../models/AzureKeyVault';
import { GoogleCloudKMS } from '../models/GoogleCloudKMS';
import { HttpFile } from '../http/http';

export class EncryptionAtRest {

    'awsKms'?: AWSKMS;

    'azureKeyVault'?: AzureKeyVault;

    'googleCloudKms'?: GoogleCloudKMS;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "awsKms",
            "baseName": "awsKms",
            "type": "AWSKMS",
            "format": ""
        },
        {
            "name": "azureKeyVault",
            "baseName": "azureKeyVault",
            "type": "AzureKeyVault",
            "format": ""
        },
        {
            "name": "googleCloudKms",
            "baseName": "googleCloudKms",
            "type": "GoogleCloudKMS",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EncryptionAtRest.attributeTypeMap;
    }

    public constructor() {
    }
}

