/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Details that define the configuration of Encryption at Rest using Google Cloud Key Management Service (KMS).
*/
export class GoogleCloudKMS {
    /**
    * Flag that indicates whether someone enabled encryption at rest for the specified  project. To disable encryption at rest using customer key management and remove the configuration details, pass only this parameter with a value of `false`.
    */

    'enabled'?: boolean;
    /**
    * Resource path that displays the key version resource ID for your Google Cloud KMS.
    */

    'keyVersionResourceID'?: string;
    /**
    * JavaScript Object Notation (JSON) object that contains the Google Cloud Key Management Service (KMS). Format the JSON as a string and not as an object.
    */

    'serviceAccountKey'?: string;
    /**
    * Flag that indicates whether the Google Cloud Key Management Service (KMS) encryption key can encrypt and decrypt data.
    */

    'valid'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "keyVersionResourceID",
            "baseName": "keyVersionResourceID",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceAccountKey",
            "baseName": "serviceAccountKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GoogleCloudKMS.attributeTypeMap;
    }

    public constructor() {
    }
}

