/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GroupMaintenanceWindow {
    /**
    * Flag that indicates whether MongoDB Cloud should defer all maintenance windows for one week after you enable them.
    */
    'autoDeferOnceEnabled'?: boolean;
    /**
    * One-based integer that represents the day of the week that the maintenance window starts.  | Value | Day of Week | |---|---| | `1` | Sunday | | `2` | Monday | | `3` | Tuesday | | `4` | Wednesday | | `5` | Thursday | | `6` | Friday | | `7` | Saturday | 
    */
    'dayOfWeek': number;
    /**
    * Zero-based integer that represents the hour of the of the day that the maintenance window starts according to a 24-hour clock. Use `0` for midnight and `12` for noon.
    */
    'hourOfDay': number;
    /**
    * Flag that indicates whether MongoDB Cloud starts the maintenance window immediately upon receiving this request. To start the maintenance window immediately for your project, MongoDB Cloud must have maintenance scheduled and you must set a maintenance window. This flag resets to `false` after MongoDB Cloud completes maintenance.
    */
    'startASAP'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "autoDeferOnceEnabled",
            "baseName": "autoDeferOnceEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dayOfWeek",
            "baseName": "dayOfWeek",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hourOfDay",
            "baseName": "hourOfDay",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startASAP",
            "baseName": "startASAP",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GroupMaintenanceWindow.attributeTypeMap;
    }

    public constructor() {
    }
}

