/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.  The Atlas Administration API uses HTTP Digest Authentication to authenticate requests. Provide a programmatic API public key and corresponding private key as the username and password when constructing the HTTP request. For example, to [return database access history](#tag/Access-Tracking/operation/listAccessLogsByClusterName) with [cURL](https://en.wikipedia.org/wiki/CURL), run the following command in the terminal:  ``` curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\   --digest \\   --header \"Accept: application/vnd.atlas.2023-02-01+json\" \\   GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/dbAccessHistory/clusters/{clusterName}?pretty=true\" ```  To learn more, see [Get Started with the Atlas Administration API](https://www.mongodb.com/docs/atlas/configure-api-access/). For support, see [MongoDB Support](https://www.mongodb.com/support/get-started).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Collection of settings that configures the project.
*/
export class GroupSettings {
    /**
    * Flag that indicates whether to collect database-specific metrics  for the specified project.
    */

    'isCollectDatabaseSpecificsStatisticsEnabled'?: boolean;
    /**
    * Flag that indicates whether to enable the Data Explorer for the specified project.
    */

    'isDataExplorerEnabled'?: boolean;
    /**
    * Flag that indicates whether to enable extended storage sizes  for the specified project.
    */

    'isExtendedStorageSizesEnabled'?: boolean;
    /**
    * Flag that indicates whether to enable the Performance Advisor and Profiler  for the specified project.
    */

    'isPerformanceAdvisorEnabled'?: boolean;
    /**
    * Flag that indicates whether to enable the Real Time Performance Panel for the specified project.
    */

    'isRealtimePerformancePanelEnabled'?: boolean;
    /**
    * Flag that indicates whether to enable the Schema Advisor for the specified project.
    */

    'isSchemaAdvisorEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isCollectDatabaseSpecificsStatisticsEnabled",
            "baseName": "isCollectDatabaseSpecificsStatisticsEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDataExplorerEnabled",
            "baseName": "isDataExplorerEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isExtendedStorageSizesEnabled",
            "baseName": "isExtendedStorageSizesEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPerformanceAdvisorEnabled",
            "baseName": "isPerformanceAdvisorEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isRealtimePerformancePanelEnabled",
            "baseName": "isRealtimePerformancePanelEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSchemaAdvisorEnabled",
            "baseName": "isSchemaAdvisorEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GroupSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

