/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DLSIngestionSink } from '../models/DLSIngestionSink';
import { PartitionField } from '../models/PartitionField';
import { HttpFile } from '../http/http';

/**
* Ingestion destination of a Data Lake Pipeline.
*/
export class IngestionSink {
    /**
    * Target cloud provider for this Data Lake Pipeline.
    */

    'metadataProvider'?: string;
    /**
    * Target cloud provider region for this Data Lake Pipeline.
    */

    'metadataRegion'?: string;
    /**
    * Ordered fields used to physically organize data in the destination.
    */

    'partitionFields'?: Array<PartitionField>;
    /**
    * Type of ingestion destination of this Data Lake Pipeline.
    */

    'type'?: string;

    static readonly discriminator: string | undefined = "type";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metadataProvider",
            "baseName": "metadataProvider",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadataRegion",
            "baseName": "metadataRegion",
            "type": "string",
            "format": ""
        },
        {
            "name": "partitionFields",
            "baseName": "partitionFields",
            "type": "Array<PartitionField>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IngestionSink.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IngestionSinkMetadataProviderEnum = "AWS" ;
export type IngestionSinkTypeEnum = "DLS" ;

