/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeMetricUnits } from '../models/TimeMetricUnits';
import { HttpFile } from '../http/http';

/**
* A Limit that triggers an alert when less than a time period.
*/
export class LessThanTimeThresholdView {
    /**
    * Comparison operator to apply when checking the current metric value.
    */
    'operator'?: LessThanTimeThresholdViewOperatorEnum;
    /**
    * Value of metric that, when exceeded, triggers an alert.
    */
    'threshold'?: number;
    'units'?: TimeMetricUnits;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "operator",
            "baseName": "operator",
            "type": "LessThanTimeThresholdViewOperatorEnum",
            "format": ""
        },
        {
            "name": "threshold",
            "baseName": "threshold",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "TimeMetricUnits",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LessThanTimeThresholdView.attributeTypeMap;
    }

    public constructor() {
    }
}


export type LessThanTimeThresholdViewOperatorEnum = "LESS_THAN" ;

