/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Unique identifier of event type.
*/
export type OrgEventTypeViewForOrg = "ORG_CREATED" | "ORG_CREDIT_CARD_ADDED" | "ORG_CREDIT_CARD_UPDATED" | "ORG_CREDIT_CARD_CURRENT" | "ORG_CREDIT_CARD_ABOUT_TO_EXPIRE" | "ORG_PAYPAL_LINKED" | "ORG_PAYPAL_UPDATED" | "ORG_PAYPAL_CANCELLED" | "ORG_OVERRIDE_PAYMENT_METHOD_ADDED" | "ORG_ACTIVATED" | "ORG_TEMPORARILY_ACTIVATED" | "ORG_SUSPENDED" | "ORG_ADMIN_SUSPENDED" | "ORG_ADMIN_LOCKED" | "ORG_CLUSTERS_DELETED" | "ORG_CLUSTERS_PAUSED" | "ORG_LOCKED" | "ORG_RENAMED" | "ALL_ORG_USERS_HAVE_MFA" | "ORG_USERS_WITHOUT_MFA" | "ORG_INVOICE_UNDER_THRESHOLD" | "ORG_INVOICE_OVER_THRESHOLD" | "ORG_DAILY_BILL_UNDER_THRESHOLD" | "ORG_DAILY_BILL_OVER_THRESHOLD" | "ORG_GROUP_CHARGES_UNDER_THRESHOLD" | "ORG_GROUP_CHARGES_OVER_THRESHOLD" | "ORG_TWO_FACTOR_AUTH_REQUIRED" | "ORG_TWO_FACTOR_AUTH_OPTIONAL" | "ORG_PUBLIC_API_ACCESS_LIST_REQUIRED" | "ORG_PUBLIC_API_ACCESS_LIST_NOT_REQUIRED" | "ORG_EMPLOYEE_ACCESS_RESTRICTED" | "ORG_EMPLOYEE_ACCESS_UNRESTRICTED" | "ORG_SFDC_ACCOUNT_ID_CHANGED" | "ORG_CONNECTED_TO_MLAB" | "ORG_DISCONNECTED_FROM_MLAB" | "ORG_IDP_CERTIFICATE_CURRENT" | "ORG_IDP_CERTIFICATE_ABOUT_TO_EXPIRE" | "ORG_CONNECTED_TO_VERCEL" | "ORG_DISCONNECTED_FROM_VERCEL" | "ORG_DISCONNECTED_TO_VERCEL" | "ORG_CONNECTION_UNINSTALLED_FROM_VERCEL" | "ORG_UI_IP_ACCESS_LIST_ENABLED" | "ORG_UI_IP_ACCESS_LIST_DISABLED" | "ORG_EDITED_UI_IP_ACCESS_LIST_ENTRIES" ;
