/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.  The Atlas Administration API uses HTTP Digest Authentication to authenticate requests. Provide a programmatic API public key and corresponding private key as the username and password when constructing the HTTP request. For example, to [return database access history](#tag/Access-Tracking/operation/listAccessLogsByClusterName) with [cURL](https://en.wikipedia.org/wiki/CURL), run the following command in the terminal:  ``` curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\   --digest \\   --header \"Accept: application/vnd.atlas.2023-02-01+json\" \\   GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/dbAccessHistory/clusters/{clusterName}?pretty=true\" ```  To learn more, see [Get Started with the Atlas Administration API](https://www.mongodb.com/docs/atlas/configure-api-access/). For support, see [MongoDB Support](https://www.mongodb.com/support/get-started).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PerformanceAdvisorIndex } from '../models/PerformanceAdvisorIndex';
import { PerformanceAdvisorShape } from '../models/PerformanceAdvisorShape';
import { HttpFile } from '../http/http';

export class PerformanceAdvisorResponse {
    /**
    * List of query predicates, sorts, and projections that the Performance Advisor suggests.
    */

    'shapes'?: Array<PerformanceAdvisorShape>;
    /**
    * List that contains the documents with information about the indexes that the Performance Advisor suggests.
    */

    'suggestedIndexes'?: Array<PerformanceAdvisorIndex>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shapes",
            "baseName": "shapes",
            "type": "Array<PerformanceAdvisorShape>",
            "format": ""
        },
        {
            "name": "suggestedIndexes",
            "baseName": "suggestedIndexes",
            "type": "Array<PerformanceAdvisorIndex>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PerformanceAdvisorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

