/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Scheduled Cloud Provider Snapshot as Source for a Data Lake Pipeline.
*/
export class PeriodicCpsSnapshotSource {
    /**
    * Human-readable name that identifies the cluster.
    */
    'clusterName'?: string;
    /**
    * Human-readable name that identifies the collection.
    */
    'collectionName'?: string;
    /**
    * Human-readable name that identifies the database.
    */
    'databaseName'?: string;
    /**
    * Unique 24-hexadecimal character string that identifies the project.
    */
    'groupId'?: string;
    /**
    * Unique 24-hexadecimal character string that identifies a policy item.
    */
    'policyItemId'?: string;
    /**
    * Type of ingestion source of this Data Lake Pipeline.
    */
    'type'?: PeriodicCpsSnapshotSourceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clusterName",
            "baseName": "clusterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionName",
            "baseName": "collectionName",
            "type": "string",
            "format": ""
        },
        {
            "name": "databaseName",
            "baseName": "databaseName",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string",
            "format": ""
        },
        {
            "name": "policyItemId",
            "baseName": "policyItemId",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PeriodicCpsSnapshotSourceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PeriodicCpsSnapshotSource.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PeriodicCpsSnapshotSourceTypeEnum = "PERIODIC_CPS" | "ON_DEMAND_CPS" ;

