/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from '../models/Link';
import { HttpFile } from '../http/http';

export class ServerlessBackupSnapshot {
    /**
    * Date and time when MongoDB Cloud took the snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    */

    'createdAt'?: Date;
    /**
    * Date and time when MongoDB Cloud deletes the snapshot. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
    */

    'expiresAt'?: Date;
    /**
    * Human-readable label that identifies how often this snapshot triggers.
    */

    'frequencyType'?: string;
    /**
    * Unique 24-hexadecimal digit string that identifies the snapshot.
    */

    'id'?: string;
    /**
    * List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    */

    'links'?: Array<Link>;
    /**
    * Version of the MongoDB host that this snapshot backs up.
    */

    'mongodVersion'?: string;
    /**
    * Human-readable label given to the serverless instance from which MongoDB Cloud took this snapshot.
    */

    'serverlessInstanceName'?: string;
    /**
    * Human-readable label that identifies when this snapshot triggers.
    */

    'snapshotType'?: string;
    /**
    * Human-readable label that indicates the stage of the backup process for this snapshot.
    */

    'status'?: string;
    /**
    * Number of bytes taken to store the backup snapshot.
    */

    'storageSizeBytes'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "frequencyType",
            "baseName": "frequencyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "mongodVersion",
            "baseName": "mongodVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverlessInstanceName",
            "baseName": "serverlessInstanceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "snapshotType",
            "baseName": "snapshotType",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "storageSizeBytes",
            "baseName": "storageSizeBytes",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ServerlessBackupSnapshot.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ServerlessBackupSnapshotFrequencyTypeEnum = "hourly" | "daily" | "weekly" | "monthly" ;
export type ServerlessBackupSnapshotSnapshotTypeEnum = "onDemand" | "scheduled" ;
export type ServerlessBackupSnapshotStatusEnum = "queued" | "inProgress" | "completed" | "failed" ;

