/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ServerlessInstanceDescriptionConnectionStringsPrivateEndpointEndpoint } from '../models/ServerlessInstanceDescriptionConnectionStringsPrivateEndpointEndpoint';
import { HttpFile } from '../http/http';

/**
* Private endpoint connection string that you can use to connect to this serverless instance through a private endpoint.
*/
export class ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint {
    /**
    * List that contains the private endpoints through which you connect to MongoDB Cloud when you use **connectionStrings.privateEndpoint[n].srvConnectionString**.
    */
    'endpoints'?: Array<ServerlessInstanceDescriptionConnectionStringsPrivateEndpointEndpoint>;
    /**
    * Private endpoint-aware connection string that uses the `mongodb+srv://` protocol to connect to MongoDB Cloud through a private endpoint. The `mongodb+srv` protocol tells the driver to look up the seed list of hosts in the Domain Name System (DNS).
    */
    'srvConnectionString'?: string;
    /**
    * MongoDB process type to which your application connects.
    */
    'type'?: ServerlessInstanceDescriptionConnectionStringsPrivateEndpointTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "endpoints",
            "baseName": "endpoints",
            "type": "Array<ServerlessInstanceDescriptionConnectionStringsPrivateEndpointEndpoint>",
            "format": ""
        },
        {
            "name": "srvConnectionString",
            "baseName": "srvConnectionString",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ServerlessInstanceDescriptionConnectionStringsPrivateEndpointTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServerlessInstanceDescriptionConnectionStringsPrivateEndpoint.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ServerlessInstanceDescriptionConnectionStringsPrivateEndpointTypeEnum = "MONGOS" ;

