/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas.  The Atlas Administration API uses HTTP Digest Authentication to authenticate requests. Provide a programmatic API public key and corresponding private key as the username and password when constructing the HTTP request. For example, to [return database access history](#tag/Access-Tracking/operation/listAccessLogsByClusterName) with [cURL](https://en.wikipedia.org/wiki/CURL), run the following command in the terminal:  ``` curl --user \"{PUBLIC-KEY}:{PRIVATE-KEY}\" \\   --digest \\   --header \"Accept: application/vnd.atlas.2023-02-01+json\" \\   GET \"https://cloud.mongodb.com/api/atlas/v2/groups/{groupId}/dbAccessHistory/clusters/{clusterName}?pretty=true\" ```  To learn more, see [Get Started with the Atlas Administration API](https://www.mongodb.com/docs/atlas/configure-api-access/). For support, see [MongoDB Support](https://www.mongodb.com/support/get-started).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from '../models/Link';
import { StreamsKafkaAuthentication } from '../models/StreamsKafkaAuthentication';
import { StreamsKafkaSecurity } from '../models/StreamsKafkaSecurity';
import { HttpFile } from '../http/http';

/**
* Settings that define a connection to an external data store.
*/
export class StreamsConnection {
    /**
    * List of one or more Uniform Resource Locators (URLs) that point to API sub-resources, related API resources, or both. RFC 5988 outlines these relationships.
    */

    'links'?: Array<Link>;
    /**
    * Human-readable label that identifies the stream connection.
    */

    'name'?: string;
    /**
    * Type of the connection. Can be either Cluster or Kafka.
    */

    'type'?: string;
    /**
    * Name of the cluster configured for this connection.
    */

    'clusterName'?: string;

    'authentication'?: StreamsKafkaAuthentication;
    /**
    * Comma separated list of server addresses.
    */

    'bootstrapServers'?: string;
    /**
    * A map of Kafka key-value pairs for optional configuration. This is a flat object, and keys can have '.' characters.
    */

    'config'?: { [key: string]: string; };

    'security'?: StreamsKafkaSecurity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<Link>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "clusterName",
            "baseName": "clusterName",
            "type": "string",
            "format": ""
        },
        {
            "name": "authentication",
            "baseName": "authentication",
            "type": "StreamsKafkaAuthentication",
            "format": ""
        },
        {
            "name": "bootstrapServers",
            "baseName": "bootstrapServers",
            "type": "string",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "security",
            "baseName": "security",
            "type": "StreamsKafkaSecurity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StreamsConnection.attributeTypeMap;
    }

    public constructor() {
    }
}

