/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Tokenizer that splits input into text chunks, or \"n-grams\", of into given sizes. You can't use the nGram tokenizer in synonym or autocomplete mapping definitions.
*/
export class TokenizernGram {
    /**
    * Characters to include in the longest token that Atlas Search creates.
    */
    'maxGram': number;
    /**
    * Characters to include in the shortest token that Atlas Search creates.
    */
    'minGram': number;
    /**
    * Human-readable label that identifies this tokenizer type.
    */
    'type': TokenizernGramTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxGram",
            "baseName": "maxGram",
            "type": "number",
            "format": ""
        },
        {
            "name": "minGram",
            "baseName": "minGram",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TokenizernGramTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TokenizernGram.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TokenizernGramTypeEnum = "edgeGram" ;

