/**
 * MongoDB Atlas Administration API
 * The MongoDB Atlas Administration API allows developers to manage all components in MongoDB Atlas. To learn more, review the [Administration API overview](https://www.mongodb.com/docs/atlas/api/atlas-admin-api/). This OpenAPI specification covers all of the collections with the exception of Alerts, Alert Configurations, and Events. Refer to the [legacy documentation](https://www.mongodb.com/docs/atlas/reference/api-resources/) for the specifications of these resources.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Tokenizer that uses a regular expression pattern to extract tokens.
*/
export class TokenizerregexCaptureGroup {
    /**
    * Index of the character group within the matching expression to extract into tokens. Use `0` to extract all character groups.
    */
    'group': number;
    /**
    * Regular expression to match against.
    */
    'pattern': string;
    /**
    * Human-readable label that identifies this tokenizer type.
    */
    'type': TokenizerregexCaptureGroupTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "number",
            "format": ""
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TokenizerregexCaptureGroupTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TokenizerregexCaptureGroup.attributeTypeMap;
    }

    public constructor() {
    }
}


export type TokenizerregexCaptureGroupTypeEnum = "regexCaptureGroup" ;

